spring.application.name=SquareEdgeSports
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://bscrexz83o1zptmnaxnt-mysql.services.clever-cloud.com:3306/bscrexz83o1zptmnaxnt?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=uplflfb4xxp4prtj
spring.datasource.password=Qdh7XEcYmewE9YdtGECt
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jackson.time-zone=Asia/Kolkata

app.jwt.secret=SquareEdgeSports@Prod#2024SuperSecureJWT!
app.jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deekshithalakshmi2@gmail.com
spring.mail.password=grvfxjixmzricsye
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.email.enabled=true
app.email.from=deekshithalakshmi2@gmail.com

app.cors.allowed-origins=https://squareedgesports-frontend.onrender.com


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

app.upload.dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.web.resources.static-locations=classpath:/static/,file:./

app.frontend.url=https://squareedgesports-frontend.onrender.com

razorpay.key.id=rzp_test_SYZn7eJogibM8A
razorpay.key.secret=SHAPdHDx0U5SSDEDX3ZGt9eV
